/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JARs;

import Controles.ControlaFornecedor;
import Controles.ControlaProdutos;
import Modelos.Fornecedor;
import Modelos.Produto;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author Marondo
 */
public class frmSelect extends javax.swing.JFrame {

    Validacoes val = new Validacoes();
    Componentes c = new Componentes();
    Fornecedor selectedForn = null;
    ControlaFornecedor conForn = new ControlaFornecedor();

    Produto selectedProd = null;
    ControlaProdutos conProd = new ControlaProdutos();
    JFrame frm;
    JTextField txtField;
    Object classe;
    int indice = 0;

    public frmSelect(JFrame frm, JTextField txtField, Object classe, JComponent orComponentTiClick) {
        initComponents();
        setSize(600, 250);
        setLocationRelativeTo(this);
//        val.disposeOnClick(this, lblOk);
        val.droaggForm(this);
        c.mudaFonte(pFundo, 18);
        thisOpen(txtField,orComponentTiClick);
        this.classe = classe;
        this.txtField = txtField;
        this.frm = frm;
        if (classe.getClass() == new Fornecedor().getClass()) {
            conForn.listarNaTabela(tab);
        } else if (classe.getClass() == new Produto().getClass()) {
            conProd.listarNaTabela(tab);
        } else {
        }

        String s = val.extraiAUltimaOcorrencia(("" + classe.getClass()), '.');
        val.poeTxt(lblClass, s + " +++");
    }
    int xm = 0, ym = 0, x = 0, y = 0;

    private void thisOpen(JTextField txtIn, JComponent c) {
        JComponent a = txtIn;
        if (c != null) {
            a = c;
        }
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xm = evt.getX();
                ym = evt.getY();
                x = evt.getXOnScreen() - xm - txtIn.getHeight()-txtIn.getWidth()/2;
                y = evt.getYOnScreen() - ym + txtIn.getHeight();
                openFrm(true, x, y);
            }
        });
    }

    public void openFrm(boolean open, int x, int y) {
        if (open) {
            setLocation(x, y);
            frm.setEnabled(false);
            setVisible(true);
        } else {
            frm.setEnabled(true);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesq = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lblClass = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout());

        pFundo.setBackground(new java.awt.Color(153, 153, 153));
        pFundo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pFundo.setLayout(new java.awt.CardLayout(2, 2));

        jPanel2.setLayout(new java.awt.BorderLayout(0, 3));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(826, 50));
        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel4.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_16.png"))); // NOI18N
        jPanel4.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setText(".");
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_START);

        txtPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqActionPerformed(evt);
            }
        });
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel4.add(txtPesq, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(35, 50));
        jPanel6.setLayout(new java.awt.CardLayout(0, 7));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ok_32.png"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, "card2");

        jPanel17.add(jPanel6, java.awt.BorderLayout.LINE_START);

        lblClass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClass.setText("Fornecedor");
        lblClass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lblClass, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel17);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRICAO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setMinWidth(50);
            tab.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pFundo.add(jPanel2, "card3");

        getContentPane().add(pFundo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqActionPerformed

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        if (classe.getClass() == new Fornecedor().getClass()) {
            pesquisarForn();
        } else if (classe.getClass() == new Produto().getClass()) {
            pesquisarProd();
        } else {

        }
    }//GEN-LAST:event_txtPesqKeyReleased

    void pesquisarForn() {
        String t = toUpperCase(val.pegaTxt(txtPesq));
        ArrayList<Fornecedor> l = new ArrayList<>();
        for (Fornecedor o : conForn.lstFornecedor()) {
            String n = toUpperCase(o.getNome());
            if (n.contains(t)) {
                l.add(o);
            }
        }
        conForn.listarNaTabela(tab, l);
    }

    void pesquisarProd() {
        String t = toUpperCase(val.pegaTxt(txtPesq));
        ArrayList<Produto> l = new ArrayList<>();
        for (Produto o : conProd.lstProduto()) {
            String n = toUpperCase(o.getNome());
            if (n.contains(t)) {
                l.add(o);
            }
        }
        conProd.listarNaTabela(tab, l);
    }
    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        if (tab.getSelectedRow() != -1) {
            indice = (Integer) tab.getValueAt(tab.getSelectedRow(), 0);
            String s = "";
            if (classe.getClass() == new Fornecedor().getClass()) {
                selectedForn = (Fornecedor) conForn.pesquisar(indice);
                if (selectedForn != null) {
                    s = selectedForn.getId() + "/" + selectedForn.getNome();
                }
            } else if (classe.getClass() == new Produto().getClass()) {
                selectedProd = (Produto) conProd.pesquisar(indice);
                if (selectedProd != null) {
                    s = selectedProd.getId() + "/" + selectedProd.getNome();
                }
            } else {
            }
            val.poeTxt(txtField, s);
            openFrm(false, x, y);
        } else {
            val.msg(tab, "Erro de listagem.");
        }
    }//GEN-LAST:event_tabMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openFrm(false, x, y);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSelect(null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClass;
    private javax.swing.JPanel pFundo;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtPesq;
    // End of variables declaration//GEN-END:variables
}
