package Visao.Paineis;

import Controles.ControlaCliente;
import JARs.Componentes;
import JARs.Validacoes;
import Modelos.Cliente;
import java.awt.Color;
import java.util.ArrayList;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

public class pClientes extends javax.swing.JPanel {

    Validacoes val = new Validacoes();
    Componentes c = new Componentes();
    ControlaCliente con = new ControlaCliente();

    Cliente selectedUser = null;
    int indice = 0;
    boolean actualizavel = false;

    public pClientes() {
        initComponents();
        c.mudaFonte(this, 18);
        con.listarNaTabela(tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtMorada = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesq = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JButton();
        btnMenu2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 180, 204));
        setLayout(new java.awt.GridLayout(1, 0, 0, 5));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.CardLayout(200, 60));

        jPanel8.setBackground(new java.awt.Color(255, 255, 230));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(425, 160));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel8.setText("Nome *");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel8);

        txtNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtNome.setOpaque(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel6.add(txtNome);

        jPanel1.add(jPanel6);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel9.setText("Morada *");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel10.add(jLabel9);

        txtMorada.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtMorada.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtMorada.setOpaque(false);
        txtMorada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoradaActionPerformed(evt);
            }
        });
        txtMorada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMoradaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMoradaKeyTyped(evt);
            }
        });
        jPanel10.add(txtMorada);

        jPanel1.add(jPanel10);

        jPanel9.add(jPanel1);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel10.setText("Contacto  *");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel12.add(jLabel10);

        txtContacto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtContacto.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtContacto.setOpaque(false);
        txtContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoActionPerformed(evt);
            }
        });
        txtContacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactoKeyTyped(evt);
            }
        });
        jPanel12.add(txtContacto);

        jPanel11.add(jPanel12);

        jPanel9.add(jPanel11);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(0, 3));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(826, 35));
        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_16.png"))); // NOI18N
        jPanel4.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setText("Nome");
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_START);

        txtPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqActionPerformed(evt);
            }
        });
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel4.add(txtPesq, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        btnSalvar.setBackground(new java.awt.Color(0, 102, 102));
        btnSalvar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addPerson.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalvar.setOpaque(false);
        btnSalvar.setPreferredSize(new java.awt.Dimension(120, 25));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalvar);

        btnMenu1.setBackground(new java.awt.Color(0, 102, 102));
        btnMenu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remov.png"))); // NOI18N
        btnMenu1.setText("Remover");
        btnMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenu1.setOpaque(false);
        btnMenu1.setPreferredSize(new java.awt.Dimension(120, 25));
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMenu1);

        btnMenu2.setBackground(new java.awt.Color(0, 102, 102));
        btnMenu2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnMenu2.setText("Limpar");
        btnMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnMenu2.setOpaque(false);
        btnMenu2.setPreferredSize(new java.awt.Dimension(120, 25));
        btnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMenu2);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        tab.setBackground(new java.awt.Color(33, 210, 224));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "Morada", "CONTACTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setMinWidth(40);
            tab.getColumnModel().getColumn(0).setPreferredWidth(40);
            tab.getColumnModel().getColumn(0).setMaxWidth(40);
            tab.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, "card2");

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqActionPerformed
    private Cliente capturaDados() {
        int id = 1;
        boolean activo = true;
        String nome = val.pegaTxt(txtNome);
        String morada = val.pegaTxt(txtMorada);
        String contacto = val.pegaTxt(txtContacto);
//        con

        if (nome.length() > 2) {
            if (morada.length() > 2) {
                if (contacto.length() == 9) {
                    return new Cliente(id, activo, nome, morada, contacto);
                } else {
                    val.errorComp(txtContacto, "Contacto invalido!", Color.WHITE);
                }
            } else {
                val.errorComp(txtMorada, "Localizacao invalida!", Color.WHITE);
            }
        } else {
            val.errorComp(txtNome, "Nome invalido!", Color.WHITE);
        }
        return null;
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Cliente u = capturaDados();
        if (u != null) {
            if (!actualizavel) {
                con.cadastrar(u);
                con.listarNaTabela(tab);
                val.msg(btnSalvar, "Salvo!");
            } else {
                int id = selectedUser.getId();
                if (id > 1) {
                    u.setId(id);
                    con.actualizar(u);
                    con.listarNaTabela(tab);
                    val.msg(btnSalvar, "Actualizado!");
                } else {
                    val.msg(btnSalvar, "Impossivel actualizar.\nEste Cliente eh padrao.!");
                }
            }
            selectedUser = null;
            actualizavel = false;
            indice = 0;
            limpar();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        if (actualizavel) {
            int id = selectedUser.getId();
            if (id != 1) {
                selectedUser.setActivo(false);
               con.actualizar(selectedUser);
                con.listarNaTabela(tab);
                val.msg(btnMenu1, "Eliminado!");
            } else {
                val.msg(btnMenu1, "Nao pode remover um Cliente padrao!");
            }
        } else {
            val.msg(btnMenu1, "Invalido.\nPesquise ou selecione um registo.");
        }
        selectedUser = null;
        actualizavel = false;
        indice = 0;
        limpar();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2ActionPerformed
        limpar();
    }//GEN-LAST:event_btnMenu2ActionPerformed

    private void txtMoradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoradaActionPerformed

    private void txtMoradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoradaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoradaKeyPressed

    private void txtMoradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoradaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoradaKeyTyped

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyTyped

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        if (tab.getSelectedRow() != -1) {
            indice = (Integer) tab.getValueAt(tab.getSelectedRow(), 0);
            selectedUser = (Cliente) con.pesquisar(indice);
            if (selectedUser != null) {
                actualizavel = true;
                preencheCampos(selectedUser);
            }
        } else {
            val.msg(tab, "Erro de listagem.");
        }
    }//GEN-LAST:event_tabMouseClicked

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        pesquisar();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqKeyReleased

    private void txtContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoActionPerformed

    private void txtContactoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoKeyPressed

    private void txtContactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoKeyTyped

    private void preencheCampos(Cliente o) {
        val.poeTxt(txtNome, o.getNome());
        val.poeTxt(txtMorada, o.getMorada());
        val.poeTxt(txtContacto, o.getContacto());
    }

    private void limpar() {
        val.poeTxt(txtNome, "");
        val.poeTxt(txtMorada, "");
        val.poeTxt(txtContacto, "");
        selectedUser = null;
        actualizavel = false;
        indice = 0;
    }

    void pesquisar() {
        String t = toUpperCase(val.pegaTxt(txtPesq));
        ArrayList<Cliente> l = new ArrayList<>();
        for (Cliente o : con.lstClientes()) {
            String n = toUpperCase(o.getNome());
            if (n.contains(t)) {
                l.add(o);
            }
        }
        con.listarNaTabela(tab, l);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnMenu2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtMorada;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesq;
    // End of variables declaration//GEN-END:variables

}
