package Visao.Paineis;

import Controles.ControlaProdutos;
import JARs.Componentes;
import JARs.DateTime;
import JARs.Validacoes;
import JARs.frmCalender;
import Modelos.Produto;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

public class pProdutos extends javax.swing.JPanel {

    Validacoes val = new Validacoes();
    Componentes c = new Componentes();
    ControlaProdutos con = new ControlaProdutos();
    DateTime dh = new DateTime();
    Produto selectedProd = null;
    int indice = 0;
    boolean actualizavel = false;

    public pProdutos(JFrame frm) {
        initComponents();
        c.mudaFonte(this, 18);
        con.listarNaTabela(tab);
        new frmCalender(frm, txtDataFabrico);
        new frmCalender(frm, txtDataValidade);
        con.fillCboForn(cboFornecedor);
        con.fillCboProd(cboNome);
        val.cbo(cboLucro, 0, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        cboNome = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cboTipoDeProd = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cboTipoDeEmbalagem = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDataFabrico = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDataValidade = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        cboFornecedor = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        txtQuantidade = new javax.swing.JTextField();
        txtValorCompra = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        cboLucro = new javax.swing.JComboBox<>();
        txtLucroCalculado = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        txtCompraUnitaria = new javax.swing.JTextField();
        txtVendaUnitaria = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesq = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnMenu2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 180, 204));
        setLayout(new java.awt.GridLayout(1, 0, 0, 5));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.CardLayout(40, 40));

        jPanel8.setBackground(new java.awt.Color(255, 255, 230));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(425, 210));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel8.setText("Nome *");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel8);

        jPanel28.setOpaque(false);
        jPanel28.setLayout(new java.awt.BorderLayout(2, 0));

        cboNome.setBackground(new java.awt.Color(0, 102, 102));
        cboNome.setEditable(true);
        cboNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descolhecido", "Blabla" }));
        cboNome.setOpaque(false);
        cboNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNomeActionPerformed(evt);
            }
        });
        jPanel28.add(cboNome, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel28);

        jPanel1.add(jPanel6);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel11.setText("Tipo de Produtos  *");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel13.add(jLabel11);

        cboTipoDeProd.setBackground(new java.awt.Color(0, 102, 102));
        cboTipoDeProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bebidas secas (Industrial)", "Bebidas secas (Artesanal)", "Bebidas Nacionais", "Bebidas Importadas" }));
        cboTipoDeProd.setOpaque(false);
        cboTipoDeProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoDeProdActionPerformed(evt);
            }
        });
        jPanel13.add(cboTipoDeProd);

        jPanel1.add(jPanel13);

        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel14.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel14.setText("Tipo de Embalagen");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel16.add(jLabel14);

        cboTipoDeEmbalagem.setBackground(new java.awt.Color(0, 102, 102));
        cboTipoDeEmbalagem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboTipoDeEmbalagem.setOpaque(false);
        cboTipoDeEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoDeEmbalagemActionPerformed(evt);
            }
        });
        jPanel16.add(cboTipoDeEmbalagem);

        jPanel1.add(jPanel16);

        jPanel9.add(jPanel1);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel9.setText("Data de Fabrico *");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel10.add(jLabel9);

        txtDataFabrico.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDataFabrico.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtDataFabrico.setOpaque(false);
        txtDataFabrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFabricoActionPerformed(evt);
            }
        });
        txtDataFabrico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataFabricoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDataFabricoKeyTyped(evt);
            }
        });
        jPanel10.add(txtDataFabrico);

        jPanel11.add(jPanel10);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel13.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel13.setText("Data de Validade");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel15.add(jLabel13);

        txtDataValidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDataValidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtDataValidade.setOpaque(false);
        txtDataValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataValidadeActionPerformed(evt);
            }
        });
        txtDataValidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDataValidadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDataValidadeKeyTyped(evt);
            }
        });
        jPanel15.add(txtDataValidade);

        jPanel11.add(jPanel15);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel21.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel21.setText("Fornecedor");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel12.add(jLabel21);

        cboFornecedor.setBackground(new java.awt.Color(0, 102, 102));
        cboFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descolhecido", "Blabla" }));
        cboFornecedor.setOpaque(false);
        cboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFornecedorActionPerformed(evt);
            }
        });
        jPanel12.add(cboFornecedor);

        jPanel11.add(jPanel12);

        jPanel9.add(jPanel11);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout(3, 0, 0, 10));

        jPanel24.setOpaque(false);
        jPanel24.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jPanel25.setOpaque(false);
        jPanel25.setLayout(new java.awt.GridLayout(1, 5, 20, 0));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel10.setText("Quantidade");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel25.add(jLabel10);

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel12.setText("Total da Compra");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel25.add(jLabel12);

        jPanel24.add(jPanel25);

        jPanel26.setOpaque(false);
        jPanel26.setLayout(new java.awt.GridLayout(1, 5, 20, 0));

        txtQuantidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtQuantidade.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtQuantidade.setOpaque(false);
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        txtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantidadeKeyTyped(evt);
            }
        });
        jPanel26.add(txtQuantidade);

        txtValorCompra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtValorCompra.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtValorCompra.setOpaque(false);
        txtValorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorCompraActionPerformed(evt);
            }
        });
        txtValorCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtValorCompraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorCompraKeyTyped(evt);
            }
        });
        jPanel26.add(txtValorCompra);

        jPanel24.add(jPanel26);

        jPanel14.add(jPanel24);

        jPanel18.setOpaque(false);
        jPanel18.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jPanel20.setOpaque(false);
        jPanel20.setLayout(new java.awt.GridLayout(1, 5, 20, 0));

        jLabel15.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel15.setText("Lucro (%)");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel20.add(jLabel15);

        jLabel17.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel17.setText("Lucro Unitario (MZ)");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel20.add(jLabel17);

        jPanel18.add(jPanel20);

        jPanel21.setOpaque(false);
        jPanel21.setLayout(new java.awt.GridLayout(1, 5, 20, 0));

        cboLucro.setBackground(new java.awt.Color(0, 102, 102));
        cboLucro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cboLucro.setOpaque(false);
        cboLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLucroActionPerformed(evt);
            }
        });
        jPanel21.add(cboLucro);

        txtLucroCalculado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLucroCalculado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtLucroCalculado.setEnabled(false);
        txtLucroCalculado.setOpaque(false);
        txtLucroCalculado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLucroCalculadoActionPerformed(evt);
            }
        });
        txtLucroCalculado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLucroCalculadoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLucroCalculadoKeyTyped(evt);
            }
        });
        jPanel21.add(txtLucroCalculado);

        jPanel18.add(jPanel21);

        jPanel14.add(jPanel18);

        jPanel19.setOpaque(false);
        jPanel19.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jPanel22.setOpaque(false);
        jPanel22.setLayout(new java.awt.GridLayout(1, 5, 20, 0));

        jLabel18.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel18.setText("Compra Unitaria(MZ)");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel22.add(jLabel18);

        jLabel16.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel16.setText("Venda Unitaria (MZ)");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel22.add(jLabel16);

        jPanel19.add(jPanel22);

        jPanel23.setOpaque(false);
        jPanel23.setLayout(new java.awt.GridLayout(1, 5, 20, 0));

        txtCompraUnitaria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCompraUnitaria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtCompraUnitaria.setEnabled(false);
        txtCompraUnitaria.setOpaque(false);
        txtCompraUnitaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCompraUnitariaActionPerformed(evt);
            }
        });
        txtCompraUnitaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCompraUnitariaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCompraUnitariaKeyTyped(evt);
            }
        });
        jPanel23.add(txtCompraUnitaria);

        txtVendaUnitaria.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtVendaUnitaria.setText("2");
        txtVendaUnitaria.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtVendaUnitaria.setEnabled(false);
        txtVendaUnitaria.setOpaque(false);
        txtVendaUnitaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVendaUnitariaActionPerformed(evt);
            }
        });
        txtVendaUnitaria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVendaUnitariaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVendaUnitariaKeyTyped(evt);
            }
        });
        jPanel23.add(txtVendaUnitaria);

        jPanel19.add(jPanel23);

        jPanel14.add(jPanel19);

        jPanel9.add(jPanel14);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(0, 3));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(826, 35));
        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_16.png"))); // NOI18N
        jPanel4.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setText("Nome");
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_START);

        txtPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqActionPerformed(evt);
            }
        });
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel4.add(txtPesq, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel27.setOpaque(false);
        jPanel27.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        btnSalvar.setBackground(new java.awt.Color(0, 102, 102));
        btnSalvar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add+.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.setOpaque(false);
        btnSalvar.setPreferredSize(new java.awt.Dimension(120, 25));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel27.add(btnSalvar);

        btnRemover.setBackground(new java.awt.Color(0, 102, 102));
        btnRemover.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remov.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.setBorder(null);
        btnRemover.setOpaque(false);
        btnRemover.setPreferredSize(new java.awt.Dimension(120, 25));
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel27.add(btnRemover);

        btnMenu2.setBackground(new java.awt.Color(0, 102, 102));
        btnMenu2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnMenu2.setText("Limpar");
        btnMenu2.setBorder(null);
        btnMenu2.setOpaque(false);
        btnMenu2.setPreferredSize(new java.awt.Dimension(120, 25));
        btnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2ActionPerformed(evt);
            }
        });
        jPanel27.add(btnMenu2);

        jPanel17.add(jPanel27, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel17);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        tab.setBackground(new java.awt.Color(33, 210, 224));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRICAO", "QUANT", "COMPRA", "LUCRO%", "VENDA", "FORNECEDOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setMinWidth(40);
            tab.getColumnModel().getColumn(0).setPreferredWidth(40);
            tab.getColumnModel().getColumn(0).setMaxWidth(40);
            tab.getColumnModel().getColumn(2).setMaxWidth(80);
            tab.getColumnModel().getColumn(3).setMaxWidth(100);
            tab.getColumnModel().getColumn(4).setMaxWidth(80);
            tab.getColumnModel().getColumn(5).setMaxWidth(100);
            tab.getColumnModel().getColumn(6).setMinWidth(240);
            tab.getColumnModel().getColumn(6).setMaxWidth(240);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, "card2");

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqActionPerformed
    private Produto capturaDados() {
        int id = 1;//con.proximoCodigo()
        boolean activo = true; 
        String nome = val.pegaTxt(cboNome);
        String tipoDeProduto = val.pegaTxt(cboTipoDeProd);
        String tipoDeEmbalagem = val.pegaTxt(cboTipoDeEmbalagem);
        String dataEntrada = dh.getData();
        String dataFabrico = val.pegaTxt(txtDataFabrico);
        String dataValidade = val.pegaTxt(txtDataValidade);
        String fornecedor = val.pegaTxt(cboFornecedor);

        int quantidade = val.e_int(txtQuantidade);
        double precoCompra = val.e_double(txtValorCompra);

        int lucro = val.e_int(val.pegaTxt(cboLucro));
        vendaContas(quantidade, precoCompra, lucro);
        double precoVenda = val.e_double(txtVendaUnitaria);
//        con

        if (nome.length() > 2) {
            if (isValidDates(dataFabrico, dataValidade)) {
                if (quantidade > 0) {
                    if (precoCompra > 0) {
                        if (precoVenda > 0) {
                            return new Produto(id, activo, nome, tipoDeProduto, tipoDeEmbalagem, dataEntrada, dataFabrico, dataValidade, fornecedor, quantidade, precoCompra, lucro, precoVenda);
                        } else {
                            val.errorComp(txtVendaUnitaria, "Preco de venda invalido!", Color.WHITE);
                        }
                    } else {
                        val.errorComp(txtValorCompra, "Preco de compra invalido!", Color.WHITE);
                    }
                } else {
                    val.errorComp(txtQuantidade, "Quantidade invalida!", Color.WHITE);
                }
            }
        } else {
            val.errorComp(cboNome, "Nome invalido!", Color.WHITE);
        }
        return null;
    }

    boolean isValidDates(String fabrico, String validade) {
        if (fabrico.length() > 0) {
            if (validade.length() > 0) {
                if (val.e_dataInferiorQueHoje(fabrico)) {
                    if (!val.e_dataInferiorQueHoje(validade)) {
                        return true;
                    } else {
                        val.errorComp(txtDataValidade, "Data de validade invalida!\nDeve ser superior que hoje.", Color.WHITE);
                    }
                } else {
                    val.errorComp(txtDataFabrico, "Data de fabrico invalida!\nNao deve ser inferior que hoje.", Color.WHITE);
                }
            } else {
                val.errorComp(txtDataValidade, "Data de validade invalida!", Color.WHITE);
            }
        } else {
            val.errorComp(txtDataFabrico, "Data de fabrico invalida!", Color.WHITE);
        }
        return false;
    }

    double vendaContas(int qtd, double valorTot, int lc) {
        String x = "0." + lc;
        if (lc < 10) {
            x = "0.0" + lc;
        }
        if (lc == 100) {
            x = "1";
        }
        double lucro = val.e_double(x);
        double a = (valorTot / qtd), b = a * lucro, c = 0, d;
        c = val.diminuiCasasDecimais((a + b) * qtd, 2);
        d = val.diminuiCasasDecimais(a + b, 2);
        b = val.diminuiCasasDecimais(b, 2);
        val.poeTxt(txtLucroCalculado, "" + b);
        val.poeTxt(txtCompraUnitaria, "" + a);
        val.poeTxt(txtVendaUnitaria, "" + d);
        return (a + b);
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Produto u = capturaDados();
        if (u != null) {
            if (!actualizavel) {
                con.cadastrar(u);
                con.listarNaTabela(tab);
                val.msg(btnSalvar, "Salvo!");
            } else {
                int id = selectedProd.getId();
                u.setId(id);
                con.actualizar(u);
                con.listarNaTabela(tab);
                val.msg(btnSalvar, "Actualizado!");

            }
            selectedProd = null;
            actualizavel = false;
            indice = 0;
            limpar();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (actualizavel) {
            int id = selectedProd.getId();
            selectedProd.setActivo(false);
            con.actualizar(selectedProd);
            con.listarNaTabela(tab);
            val.msg(btnRemover, "Eliminado!");
        } else {
            val.msg(btnRemover, "Invalido.\nPesquise ou selecione um registo.");
        }
        selectedProd = null;
        actualizavel = false;
        indice = 0;
        limpar();
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2ActionPerformed
        limpar();
    }//GEN-LAST:event_btnMenu2ActionPerformed

    private void txtDataFabricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFabricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFabricoActionPerformed

    private void txtDataFabricoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataFabricoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFabricoKeyPressed

    private void txtDataFabricoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataFabricoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFabricoKeyTyped

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        if (tab.getSelectedRow() != -1) {
            indice = (Integer) tab.getValueAt(tab.getSelectedRow(), 0);
            selectedProd = (Produto) con.pesquisar(indice);
            if (selectedProd != null) {
                actualizavel = true;
                preencheCampos(selectedProd);
            }
        } else {
            val.msg(tab, "Erro de listagem.");
        }
    }//GEN-LAST:event_tabMouseClicked

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        pesquisar();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqKeyReleased

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeKeyPressed

    private void txtQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantidadeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeKeyTyped

    private void cboTipoDeProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDeProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoDeProdActionPerformed

    private void txtDataValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataValidadeActionPerformed

    private void txtDataValidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataValidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataValidadeKeyPressed

    private void txtDataValidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDataValidadeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataValidadeKeyTyped

    private void cboTipoDeEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoDeEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoDeEmbalagemActionPerformed

    private void txtValorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompraActionPerformed

    private void txtValorCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCompraKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompraKeyPressed

    private void txtValorCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCompraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorCompraKeyTyped

    private void txtLucroCalculadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLucroCalculadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroCalculadoActionPerformed

    private void txtLucroCalculadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLucroCalculadoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroCalculadoKeyPressed

    private void txtLucroCalculadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLucroCalculadoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroCalculadoKeyTyped

    private void txtVendaUnitariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVendaUnitariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendaUnitariaActionPerformed

    private void txtVendaUnitariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVendaUnitariaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendaUnitariaKeyPressed

    private void txtVendaUnitariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVendaUnitariaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVendaUnitariaKeyTyped

    private void txtCompraUnitariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompraUnitariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompraUnitariaActionPerformed

    private void txtCompraUnitariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompraUnitariaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompraUnitariaKeyPressed

    private void txtCompraUnitariaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCompraUnitariaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompraUnitariaKeyTyped

    private void cboLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLucroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLucroActionPerformed

    private void cboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboFornecedorActionPerformed

    private void cboNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNomeActionPerformed

    private void preencheCampos(Produto o) {
        val.poeTxt(cboNome, o.getNome());
        val.poeTxt(cboTipoDeProd, o.getTipoDeProduto());
        val.poeTxt(cboTipoDeEmbalagem, o.getTipoDeEmbalagem());
        val.poeTxt(txtDataFabrico, o.getDataFabrico());
        val.poeTxt(txtDataValidade, o.getDataValidade());
        val.poeTxt(cboFornecedor, o.getFornecedor());

        val.poeTxt(txtQuantidade, "" + o.getQuantidade());
        val.poeTxt(txtValorCompra, "" + o.getPrecoCompra());
        val.poeTxt(txtVendaUnitaria, "" + o.getPrecoVenda());

        val.poeTxt(cboLucro, "" + o.getLucro());
        vendaContas(o.getQuantidade(), o.getPrecoCompra(), o.getLucro());
    }

    private void limpar() {
        val.poeTxt(cboNome, "");
        val.poeTxt(txtDataFabrico, "");
        val.poeTxt(txtDataValidade, "");
        val.poeTxt(cboFornecedor, "Desconhecido");

        val.poeTxt(txtQuantidade, "1");
        val.poeTxt(txtValorCompra, "0");
        val.poeTxt(txtVendaUnitaria, "0");
        val.poeTxt(txtLucroCalculado, "0");
        val.poeTxt(txtCompraUnitaria, "0");
        selectedProd = null;
        actualizavel = false;
        indice = 0;
    }

    void pesquisar() {
        String t = toUpperCase(val.pegaTxt(txtPesq));
        ArrayList<Produto> l = new ArrayList<>();
        for (Produto o : con.lstProduto()) {
            String n = toUpperCase(o.getNome());
            if (n.contains(t)) {
                l.add(o);
            }
        }
        con.listarNaTabela(tab, l);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu2;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboFornecedor;
    private javax.swing.JComboBox<String> cboLucro;
    private javax.swing.JComboBox<String> cboNome;
    private javax.swing.JComboBox<String> cboTipoDeEmbalagem;
    private javax.swing.JComboBox<String> cboTipoDeProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtCompraUnitaria;
    private javax.swing.JTextField txtDataFabrico;
    private javax.swing.JTextField txtDataValidade;
    private javax.swing.JTextField txtLucroCalculado;
    private javax.swing.JTextField txtPesq;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorCompra;
    private javax.swing.JTextField txtVendaUnitaria;
    // End of variables declaration//GEN-END:variables

}
