/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Paineis;

import Controles.ControlaProdutos;
import Controles.ControlaVenda;
import Controles.iReport.Imprimir;
import JARs.Componentes;
import JARs.Validacoes;
import JARs.frmCalender;
import Modelos.Produto;
import Modelos.Venda;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Marondo
 */
public class pRelatorios extends javax.swing.JPanel {

    Validacoes val = new Validacoes();
    Componentes c = new Componentes();
    ControlaProdutos conProd = new ControlaProdutos();
    ControlaVenda conVenda = new ControlaVenda();
    Imprimir imp = new Imprimir();
    public ArrayList<Venda> lstCarregarVend = new ArrayList<>();
    public ArrayList<Produto> lstCarregarProd = new ArrayList<>();

    public pRelatorios(JFrame frm) {
        initComponents();
        c.mudaFonte(pProdutos, 18);
        c.mudaFonte(pVendas, 18);
        pesquisarVenda();;
        pesquisarProd();;
        conProd.fillCbo_Forn_Emb_Tipo(cboFornecedorProd, cboEmbProd, cboTipoProd);
        new frmCalender(frm, txtDataInicioVend);
        new frmCalender(frm, txtDataFimVend);

        new frmCalender(frm, txtDataFimProd);
        new frmCalender(frm, txtDataInicioProd);
        pesquisarProd();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        pProdutos = new javax.swing.JPanel();
        pFundoProd = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        cboFornecedorProd = new javax.swing.JComboBox<>();
        jPanel37 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        cboEmbProd = new javax.swing.JComboBox<>();
        jPanel38 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        cboTipoProd = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtDataInicioProd = new javax.swing.JTextField();
        jPanel24 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtDataFimProd = new javax.swing.JTextField();
        jPanel39 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtPesqProd = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        btnImprimir2 = new javax.swing.JButton();
        btnImprimir3 = new javax.swing.JButton();
        btnCalcular1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblTotalProd = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabProd = new javax.swing.JTable();
        pVendas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboClienteVend = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboEstadoVend = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDataInicioVend = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDataFimVend = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPesqVend = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        btnImprimir1 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabVendas = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblTotalVend = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 180, 204));
        setLayout(new java.awt.CardLayout(10, 10));

        jTabbedPane2.setBackground(new java.awt.Color(0, 180, 204));
        jTabbedPane2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTabbedPane2.setOpaque(true);

        pProdutos.setBackground(new java.awt.Color(0, 180, 204));
        pProdutos.setLayout(new java.awt.GridLayout(1, 2, 2, 0));

        pFundoProd.setBackground(new java.awt.Color(0, 180, 204));
        pFundoProd.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel3.setMinimumSize(new java.awt.Dimension(100, 110));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(821, 115));
        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 0, 3));

        jPanel35.setOpaque(false);
        jPanel35.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        jPanel36.setOpaque(false);
        jPanel36.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel20.setText("Forncdr");
        jPanel36.add(jLabel20, java.awt.BorderLayout.LINE_START);

        cboFornecedorProd.setBackground(new java.awt.Color(0, 102, 102));
        cboFornecedorProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboFornecedorProd.setOpaque(false);
        cboFornecedorProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFornecedorProdActionPerformed(evt);
            }
        });
        jPanel36.add(cboFornecedorProd, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel36);

        jPanel37.setOpaque(false);
        jPanel37.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel21.setText("Emb");
        jPanel37.add(jLabel21, java.awt.BorderLayout.LINE_START);

        cboEmbProd.setBackground(new java.awt.Color(0, 102, 102));
        cboEmbProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboEmbProd.setOpaque(false);
        cboEmbProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmbProdActionPerformed(evt);
            }
        });
        jPanel37.add(cboEmbProd, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel37);

        jPanel38.setOpaque(false);
        jPanel38.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel22.setText("Tipo");
        jPanel38.add(jLabel22, java.awt.BorderLayout.LINE_START);

        cboTipoProd.setBackground(new java.awt.Color(0, 102, 102));
        cboTipoProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboTipoProd.setOpaque(false);
        cboTipoProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoProdActionPerformed(evt);
            }
        });
        jPanel38.add(cboTipoProd, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel38);

        jPanel23.setOpaque(false);
        jPanel23.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel12.setText("De data");
        jPanel23.add(jLabel12, java.awt.BorderLayout.LINE_START);

        txtDataInicioProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicioProdActionPerformed(evt);
            }
        });
        jPanel23.add(txtDataInicioProd, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel23);

        jPanel24.setOpaque(false);
        jPanel24.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel13.setText("Ate data");
        jPanel24.add(jLabel13, java.awt.BorderLayout.LINE_START);

        txtDataFimProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFimProdActionPerformed(evt);
            }
        });
        jPanel24.add(txtDataFimProd, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel24);

        jPanel39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel39.setOpaque(false);
        jPanel39.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel39.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_16.png"))); // NOI18N
        jPanel39.add(jLabel23, java.awt.BorderLayout.LINE_END);

        jLabel24.setText("Nome");
        jPanel39.add(jLabel24, java.awt.BorderLayout.LINE_START);

        txtPesqProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqProdActionPerformed(evt);
            }
        });
        txtPesqProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqProdKeyReleased(evt);
            }
        });
        jPanel39.add(txtPesqProd, java.awt.BorderLayout.CENTER);

        jPanel35.add(jPanel39);

        jPanel3.add(jPanel35);
        jPanel3.add(jLabel19);

        jPanel27.setOpaque(false);
        jPanel27.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel27.add(jLabel16);

        jPanel28.setOpaque(false);
        jPanel28.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel27.add(jPanel28);

        jPanel29.setOpaque(false);
        jPanel29.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel27.add(jPanel29);

        jPanel30.setOpaque(false);
        jPanel30.setLayout(new java.awt.GridLayout(1, 4, 4, 0));

        btnImprimir2.setBackground(new java.awt.Color(0, 153, 102));
        btnImprimir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnImprimir2.setText("Refresh");
        btnImprimir2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimir2.setOpaque(false);
        btnImprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir2ActionPerformed(evt);
            }
        });
        jPanel30.add(btnImprimir2);

        jPanel27.add(jPanel30);

        btnImprimir3.setBackground(new java.awt.Color(0, 153, 102));
        btnImprimir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnImprimir3.setText("Limpar");
        btnImprimir3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimir3.setOpaque(false);
        btnImprimir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir3ActionPerformed(evt);
            }
        });
        jPanel27.add(btnImprimir3);

        btnCalcular1.setBackground(new java.awt.Color(0, 153, 102));
        btnCalcular1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calcular.png"))); // NOI18N
        btnCalcular1.setText("Gerar Relatorio");
        btnCalcular1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCalcular1.setOpaque(false);
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });
        jPanel27.add(btnCalcular1);

        jPanel3.add(jPanel27);

        pFundoProd.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel31.setBackground(new java.awt.Color(0, 160, 230));
        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel31.setPreferredSize(new java.awt.Dimension(821, 30));
        jPanel31.setLayout(new java.awt.GridLayout(1, 3, 10, 0));
        jPanel31.add(jLabel17);

        jPanel32.setOpaque(false);
        jPanel32.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel31.add(jPanel32);

        jPanel33.setOpaque(false);
        jPanel33.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel31.add(jPanel33);

        jPanel34.setOpaque(false);
        jPanel34.setLayout(new java.awt.GridLayout(1, 4, 4, 0));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("TOTAL:   ");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel34.add(jLabel18);

        lblTotalProd.setText("0");
        jPanel34.add(lblTotalProd);

        jPanel31.add(jPanel34);

        jPanel4.add(jPanel31, java.awt.BorderLayout.PAGE_END);

        tabProd.setBackground(new java.awt.Color(33, 210, 224));
        tabProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRICAO", "QUANT", "COMPRA", "LUCRO%", "VENDA", "FORNECEDOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabProdMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabProd);
        if (tabProd.getColumnModel().getColumnCount() > 0) {
            tabProd.getColumnModel().getColumn(0).setMinWidth(40);
            tabProd.getColumnModel().getColumn(0).setMaxWidth(40);
            tabProd.getColumnModel().getColumn(2).setMinWidth(80);
            tabProd.getColumnModel().getColumn(2).setMaxWidth(80);
            tabProd.getColumnModel().getColumn(3).setMinWidth(80);
            tabProd.getColumnModel().getColumn(3).setMaxWidth(80);
            tabProd.getColumnModel().getColumn(4).setMinWidth(80);
            tabProd.getColumnModel().getColumn(4).setMaxWidth(80);
            tabProd.getColumnModel().getColumn(5).setMinWidth(80);
            tabProd.getColumnModel().getColumn(5).setMaxWidth(80);
        }

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        pFundoProd.add(jPanel4, java.awt.BorderLayout.CENTER);

        pProdutos.add(pFundoProd);

        jTabbedPane2.addTab("       Produtos       ", pProdutos);

        pVendas.setBackground(new java.awt.Color(0, 180, 204));
        pVendas.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel1.setMinimumSize(new java.awt.Dimension(100, 110));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(821, 115));
        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 0, 3));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel2.setText("Cliente");
        jPanel6.add(jLabel2, java.awt.BorderLayout.LINE_START);

        cboClienteVend.setBackground(new java.awt.Color(0, 102, 102));
        cboClienteVend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboClienteVend.setOpaque(false);
        cboClienteVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClienteVendActionPerformed(evt);
            }
        });
        jPanel6.add(cboClienteVend, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel3.setText("Estado");
        jPanel7.add(jLabel3, java.awt.BorderLayout.LINE_START);

        cboEstadoVend.setBackground(new java.awt.Color(0, 102, 102));
        cboEstadoVend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboEstadoVend.setOpaque(false);
        cboEstadoVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEstadoVendActionPerformed(evt);
            }
        });
        jPanel7.add(cboEstadoVend, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel4.setText("De data");
        jPanel17.add(jLabel4, java.awt.BorderLayout.LINE_START);

        txtDataInicioVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataInicioVendActionPerformed(evt);
            }
        });
        jPanel17.add(txtDataInicioVend, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel17);

        jPanel18.setOpaque(false);
        jPanel18.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel9.setText("Ate data");
        jPanel18.add(jLabel9, java.awt.BorderLayout.LINE_START);

        txtDataFimVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataFimVendActionPerformed(evt);
            }
        });
        jPanel18.add(txtDataFimVend, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel18);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel12.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_16.png"))); // NOI18N
        jPanel12.add(jLabel6, java.awt.BorderLayout.LINE_END);

        jLabel7.setText("Produto");
        jPanel12.add(jLabel7, java.awt.BorderLayout.LINE_START);

        txtPesqVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqVendActionPerformed(evt);
            }
        });
        txtPesqVend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqVendKeyReleased(evt);
            }
        });
        jPanel12.add(txtPesqVend, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel12);

        jPanel1.add(jPanel5);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel1.add(jPanel13);

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel14.add(jLabel10);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel14.add(jPanel15);

        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel14.add(jPanel16);

        jPanel19.setOpaque(false);
        jPanel19.setLayout(new java.awt.GridLayout(1, 4, 4, 0));

        btnImprimir1.setBackground(new java.awt.Color(0, 153, 102));
        btnImprimir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnImprimir1.setText("Refresh");
        btnImprimir1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimir1.setOpaque(false);
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });
        jPanel19.add(btnImprimir1);

        jPanel14.add(jPanel19);

        btnImprimir.setBackground(new java.awt.Color(0, 153, 102));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnImprimir.setText("Limpar");
        btnImprimir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimir.setOpaque(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel14.add(btnImprimir);

        btnCalcular.setBackground(new java.awt.Color(0, 153, 102));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calcular.png"))); // NOI18N
        btnCalcular.setText("Gerar Relatorio");
        btnCalcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCalcular.setOpaque(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel14.add(btnCalcular);

        jPanel1.add(jPanel14);

        pVendas.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(0, 5));

        tabVendas.setBackground(new java.awt.Color(33, 210, 224));
        tabVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUTO", "CLIENTE", "QTD", "V. UNITARIO", "TOTAL", "DATA", "ESTADO", "USUARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabVendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabVendas);
        if (tabVendas.getColumnModel().getColumnCount() > 0) {
            tabVendas.getColumnModel().getColumn(0).setMinWidth(40);
            tabVendas.getColumnModel().getColumn(0).setMaxWidth(40);
            tabVendas.getColumnModel().getColumn(3).setMinWidth(70);
            tabVendas.getColumnModel().getColumn(3).setPreferredWidth(70);
            tabVendas.getColumnModel().getColumn(3).setMaxWidth(70);
            tabVendas.getColumnModel().getColumn(4).setMinWidth(90);
            tabVendas.getColumnModel().getColumn(4).setPreferredWidth(90);
            tabVendas.getColumnModel().getColumn(4).setMaxWidth(90);
            tabVendas.getColumnModel().getColumn(5).setMinWidth(90);
            tabVendas.getColumnModel().getColumn(5).setMaxWidth(90);
            tabVendas.getColumnModel().getColumn(7).setMinWidth(90);
            tabVendas.getColumnModel().getColumn(7).setMaxWidth(100);
            tabVendas.getColumnModel().getColumn(8).setMinWidth(100);
            tabVendas.getColumnModel().getColumn(8).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.setBackground(new java.awt.Color(0, 160, 230));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel8.setPreferredSize(new java.awt.Dimension(821, 30));
        jPanel8.setLayout(new java.awt.GridLayout(1, 3, 10, 0));
        jPanel8.add(jLabel1);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel8.add(jPanel9);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(1, 4, 4, 0));
        jPanel8.add(jPanel10);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 4, 4, 0));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("TOTAL:   ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel11.add(jLabel5);

        lblTotalVend.setText("0");
        jPanel11.add(lblTotalVend);

        jPanel8.add(jPanel11);

        jPanel2.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        pVendas.add(jPanel2, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("         Vendas         ", pVendas);

        add(jTabbedPane2, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void tabVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVendasMouseClicked
//        if (tabVendas.getSelectedRow() != -1) {
//            indice = (Integer) tabVendas.getValueAt(tabVendas.getSelectedRow(), 0);
//            Venda v = lstCarregarVend.get(indice - 1);
//            if (v != null) {
//                limpar(v);
//            }
//        } else {
//            val.msg(tabVendas, "Erro de listagem.");
//        }
    }//GEN-LAST:event_tabVendasMouseClicked

    private void cboClienteVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteVendActionPerformed
        pesquisarVenda();
    }//GEN-LAST:event_cboClienteVendActionPerformed

    private void cboEstadoVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEstadoVendActionPerformed
        pesquisarVenda();
    }//GEN-LAST:event_cboEstadoVendActionPerformed

    private void txtPesqVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqVendActionPerformed

    }//GEN-LAST:event_txtPesqVendActionPerformed
    void pesquisarVenda() {
        String cliente = val.pegaTxt(cboClienteVend);
        String estado = val.pegaTxt(cboEstadoVend);
        String dataIn = val.pegaTxt(txtDataInicioVend);
        String dataF = val.pegaTxt(txtDataFimVend);
        String searc = val.pegaTxt(txtPesqVend);
        lstCarregarVend = conVenda.listarNaTabelaRelatorio(tabVendas, cliente, estado, dataIn, dataF, searc);
        val.poeTxt(lblTotalVend, "" + lstCarregarVend.size());
    }

    void pesquisarProd() {
        String fornecedor = val.pegaTxt(cboFornecedorProd);
        String embalagem = val.pegaTxt(cboEmbProd);
        String tipo = val.pegaTxt(cboTipoProd);
        String dataInProd = val.pegaTxt(txtDataInicioProd);
        String dataFimProd = val.pegaTxt(txtDataFimProd);
        String searcProd = val.pegaTxt(txtPesqProd);
        lstCarregarProd = conProd.listarNaTabelaRelatorio(tabProd, fornecedor, embalagem, tipo, dataInProd, dataFimProd, searcProd);
        val.poeTxt(lblTotalProd, "" + lstCarregarProd.size());
    }
    private void txtPesqVendKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqVendKeyReleased
        pesquisarVenda();
    }//GEN-LAST:event_txtPesqVendKeyReleased

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        imp.imprimirVenda(lstCarregarVend, true);
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        limparVenda();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtDataInicioVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicioVendActionPerformed
        pesquisarVenda();        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicioVendActionPerformed

    private void txtDataFimVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFimVendActionPerformed
        pesquisarVenda();        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFimVendActionPerformed

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
         pesquisarVenda();
        conVenda.fillCbo_Cli_Est(cboClienteVend, cboEstadoVend);
    }//GEN-LAST:event_btnImprimir1ActionPerformed

    private void txtDataInicioProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataInicioProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataInicioProdActionPerformed

    private void txtDataFimProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataFimProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataFimProdActionPerformed

    private void btnImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir2ActionPerformed
        pesquisarProd();
        conProd.fillCbo_Forn_Emb_Tipo(cboFornecedorProd, cboEmbProd, cboTipoProd);
    }//GEN-LAST:event_btnImprimir2ActionPerformed

    private void btnImprimir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir3ActionPerformed
        limparProd();
    }//GEN-LAST:event_btnImprimir3ActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        imp.imprimirProduto(lstCarregarProd, true);
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void cboFornecedorProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFornecedorProdActionPerformed
        pesquisarProd();
    }//GEN-LAST:event_cboFornecedorProdActionPerformed

    private void cboEmbProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmbProdActionPerformed
        pesquisarProd();
    }//GEN-LAST:event_cboEmbProdActionPerformed

    private void cboTipoProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoProdActionPerformed
        pesquisarProd();
    }//GEN-LAST:event_cboTipoProdActionPerformed

    private void txtPesqProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqProdActionPerformed

    }//GEN-LAST:event_txtPesqProdActionPerformed

    private void txtPesqProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqProdKeyReleased
        pesquisarProd();
    }//GEN-LAST:event_txtPesqProdKeyReleased

    private void tabProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabProdMouseClicked
//        if (tabProd.getSelectedRow() != -1) {
//            indice = (Integer) tabProd.getValueAt(tabProd.getSelectedRow(), 0);
//            selectedProd = (Produto) con.pesquisar(indice);
//            if (selectedProd != null) {
//                actualizavel = true;
//                preencheCampos(selectedProd);
//            }
//        } else {
//            val.msg(tabProd, "Erro de listagem.");
//        }
    }//GEN-LAST:event_tabProdMouseClicked
    void limparVenda() {
        val.poeTxt(cboClienteVend, "Todos");
        val.poeTxt(cboEstadoVend, "Todos");
        val.poeTxt(txtDataInicioVend, "");
        val.poeTxt(txtDataFimVend, "");
        pesquisarVenda();
        conVenda.fillCbo_Cli_Est(cboClienteVend, cboEstadoVend);
    }

    void limparProd() {
        val.poeTxt(cboFornecedorProd, "Todos");
        val.poeTxt(cboEmbProd, "Todos");
        val.poeTxt(cboTipoProd, "Todos");
        val.poeTxt(txtDataInicioProd, "");
        val.poeTxt(txtDataFimProd, "");
        pesquisarVenda();
        conVenda.fillCbo_Cli_Est(cboClienteVend, cboEstadoVend);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnImprimir2;
    private javax.swing.JButton btnImprimir3;
    private javax.swing.JComboBox<String> cboClienteVend;
    private javax.swing.JComboBox<String> cboEmbProd;
    private javax.swing.JComboBox<String> cboEstadoVend;
    private javax.swing.JComboBox<String> cboFornecedorProd;
    private javax.swing.JComboBox<String> cboTipoProd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblTotalProd;
    private javax.swing.JLabel lblTotalVend;
    private javax.swing.JPanel pFundoProd;
    private javax.swing.JPanel pProdutos;
    private javax.swing.JPanel pVendas;
    private javax.swing.JTable tabProd;
    private javax.swing.JTable tabVendas;
    private javax.swing.JTextField txtDataFimProd;
    private javax.swing.JTextField txtDataFimVend;
    private javax.swing.JTextField txtDataInicioProd;
    private javax.swing.JTextField txtDataInicioVend;
    private javax.swing.JTextField txtPesqProd;
    private javax.swing.JTextField txtPesqVend;
    // End of variables declaration//GEN-END:variables
}
