package Visao.Paineis;
 
import Controles.ControlaUsuario;
import JARs.Componentes;
import JARs.Validacoes;
import Modelos.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import jdk.nashorn.internal.objects.NativeString;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

public class pUsuarios extends javax.swing.JPanel {

    Validacoes val = new Validacoes();
    Componentes c = new Componentes();
    ControlaUsuario con = new ControlaUsuario();

    Usuario selectedUser = null;
    int indice = 0;
    boolean actualizavel = false;

    public pUsuarios() {
        initComponents();
        c.mudaFonte(this, 18);
        con.listarNaTabela(tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        txtSenha = new javax.swing.JPasswordField();
        txtSenhaConfirm = new javax.swing.JPasswordField();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cboTipoUser = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesq = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JButton();
        btnMenu2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 180, 204));
        setLayout(new java.awt.GridLayout(1, 0, 0, 5));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.CardLayout(200, 60));

        jPanel8.setBackground(new java.awt.Color(0, 180, 204));
        jPanel8.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(425, 160));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2, 30, 0));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel8.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel8.setText("Nome completo");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel6.add(jLabel8);

        txtNome.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtNome.setOpaque(false);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel6.add(txtNome);

        jPanel1.add(jPanel6);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel9.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel9.setText("Nome de usuario");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel10.add(jLabel9);

        txtUser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUser.setOpaque(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUserKeyTyped(evt);
            }
        });
        jPanel10.add(txtUser);

        jPanel1.add(jPanel10);

        jPanel9.add(jPanel1);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        jLabel10.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel10.setText("Senha");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel14.add(jLabel10);

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel11.setText("Confirmar senha");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel14.add(jLabel11);

        jPanel12.add(jPanel14);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        txtSenha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSenha.setOpaque(false);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel15.add(txtSenha);

        txtSenhaConfirm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSenhaConfirm.setOpaque(false);
        txtSenhaConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaConfirmActionPerformed(evt);
            }
        });
        jPanel15.add(txtSenhaConfirm);

        jPanel12.add(jPanel15);

        jPanel11.add(jPanel12);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.GridLayout(2, 0, 0, 2));

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel12.setText("Tipo de Usuario");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel13.add(jLabel12);

        cboTipoUser.setBackground(new java.awt.Color(0, 102, 102));
        cboTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caixa", "Moderador" }));
        cboTipoUser.setOpaque(false);
        cboTipoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoUserActionPerformed(evt);
            }
        });
        jPanel13.add(cboTipoUser);

        jPanel11.add(jPanel13);

        jPanel9.add(jPanel11);

        jPanel8.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(0, 3));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(826, 35));
        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel4.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_16.png"))); // NOI18N
        jPanel4.add(jLabel1, java.awt.BorderLayout.LINE_END);

        jLabel2.setText("Nome");
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_START);

        txtPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqActionPerformed(evt);
            }
        });
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel4.add(txtPesq, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        btnSalvar.setBackground(new java.awt.Color(0, 102, 102));
        btnSalvar.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/addPerson.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setBorder(null);
        btnSalvar.setOpaque(false);
        btnSalvar.setPreferredSize(new java.awt.Dimension(120, 25));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel5.add(btnSalvar);

        btnMenu1.setBackground(new java.awt.Color(0, 102, 102));
        btnMenu1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remov.png"))); // NOI18N
        btnMenu1.setText("Remover");
        btnMenu1.setBorder(null);
        btnMenu1.setOpaque(false);
        btnMenu1.setPreferredSize(new java.awt.Dimension(120, 25));
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMenu1);

        btnMenu2.setBackground(new java.awt.Color(0, 102, 102));
        btnMenu2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnMenu2.setText("Limpar");
        btnMenu2.setBorder(null);
        btnMenu2.setOpaque(false);
        btnMenu2.setPreferredSize(new java.awt.Dimension(120, 25));
        btnMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu2ActionPerformed(evt);
            }
        });
        jPanel5.add(btnMenu2);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        tab.setBackground(new java.awt.Color(33, 210, 224));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "USER", "TIPO DE USUARIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setMinWidth(40);
            tab.getColumnModel().getColumn(0).setPreferredWidth(40);
            tab.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, "card2");

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqActionPerformed
    private Usuario capturaDados() {
        int id =1;
        boolean activo = true;
        String nome = val.pegaTxt(txtNome);
        String user = val.pegaTxt(txtUser);
        String pass = val.pegaTxt(txtSenha);
        String pass2 = val.pegaTxt(txtSenhaConfirm);
        String tipo = val.pegaTxt(cboTipoUser);
//        con

        if (nome.length() > 2) {
            if (user.length() > 2) {
                if (pass.length() > 4) {
                    if (pass.equals(pass2)) {
                        return new Usuario(id, activo, nome, user, pass, tipo);
                    } else {
                        val.errorComp(txtSenha, "As duas senhas devem ser iguais.", Color.WHITE);
                        val.errorComp(txtSenhaConfirm, "", Color.WHITE);
                    }
                } else {
                    val.errorComp(txtSenha, "Senha invalida!\nMinimo de digitos = 5", Color.WHITE);
                }
            } else {
                val.errorComp(txtUser, "Nome de usuario invalido!", Color.WHITE);
            }
        } else {
            val.errorComp(txtNome, "Nome invalido!", Color.WHITE);
        }
        return null;
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
         Usuario u = capturaDados();
        if (u != null) {
            if (!actualizavel) {
                con.cadastrar(u);
                con.listarNaTabela(tab);
                val.msg(btnSalvar, "Salvo!");
            } else {
                int id = selectedUser.getId();
                u.setId(id);
                String tipo = selectedUser.getTipo();
                if (tipo.equalsIgnoreCase("admin")) {
                    u.setTipo(tipo);
                }
                con.actualizar( u);
                con.listarNaTabela(tab);
                val.msg(btnSalvar, "Actualizado!");
            }
            selectedUser = null;
            actualizavel = false;
            indice = 0;
            limpar();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        if (actualizavel) {
            int id = selectedUser.getId();
            if (id != 1) {
                selectedUser.setActivo(false);
                con.actualizar( selectedUser);
                con.listarNaTabela(tab);
                val.msg(btnMenu1, "Eliminado!");
            } else {
                val.msg(btnMenu1, "Nao pode remover o administrador!");
            }
        } else {
            val.msg(btnMenu1, "Invalido.\nPesquise ou selecione um registo.");
        }
        selectedUser = null;
        actualizavel = false;
        indice = 0;
        limpar();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu2ActionPerformed
        limpar();
    }//GEN-LAST:event_btnMenu2ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserKeyTyped

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void txtSenhaConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaConfirmActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeKeyTyped

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        if (tab.getSelectedRow() != -1) {
            indice = (Integer) tab.getValueAt(tab.getSelectedRow(), 0);
            selectedUser = (Usuario) con.pesquisar(indice );
            if (selectedUser != null) {
                actualizavel = true;
                preencheCampos(selectedUser);
            }
        } else {
            val.msg(tab, "Erro de listagem.");
        }
    }//GEN-LAST:event_tabMouseClicked

    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
        pesquisar();        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesqKeyReleased

    private void cboTipoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTipoUserActionPerformed

    private void preencheCampos(Usuario o) {
        val.poeTxt(txtNome, o.getNome());
        val.poeTxt(txtUser, o.getUser());
        val.poeTxt(txtSenha, o.getPass());
        val.poeTxt(txtSenhaConfirm, o.getPass());
    }

    private void limpar() {
        val.poeTxt(txtNome, "");
        val.poeTxt(txtUser, "");
        val.poeTxt(txtSenha, "");
        val.poeTxt(txtSenhaConfirm, "");
        selectedUser = null;
        actualizavel = false;
        indice = 0;
    }

    void pesquisar() {
        String t = toUpperCase(val.pegaTxt(txtPesq));
        ArrayList<Usuario> l = new ArrayList<>();
        for (Usuario o : con.lstUsuarios()) {
            String n = toUpperCase(o.getNome());
            if (n.contains(t)) {
                l.add(o);
            }
        }
        con.listarNaTabela(tab, l);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnMenu2;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cboTipoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesq;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JPasswordField txtSenhaConfirm;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

}
