package Visao.Paineis;

import Controles.ControlaFornecedor;
import Controles.ControlaProdutos;
import Controles.ControlaVenda;
import Controles.iReport.Imprimir;
import JARs.Componentes;
import JARs.DateTime;
import JARs.Extenso;
import JARs.Validacoes;
import Modelos.Fornecedor;
import Modelos.Produto;
import Modelos.Usuario;
import Modelos.Venda;
import Visao.frmCarregarProd;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

public class pVendas extends javax.swing.JPanel {

    Validacoes val = new Validacoes();
    Componentes c = new Componentes();
    ControlaProdutos conProd = new ControlaProdutos();
    ControlaVenda conVenda = new ControlaVenda();

    Imprimir imp = new Imprimir();
    int indice = 0;
    boolean actualizavel = false;

    JFrame frm;
    DateTime dh = new DateTime();

    public ArrayList<Venda> lstCarregar = new ArrayList<>();
    String usuario;

    public pVendas(JFrame frm, String user) {
        initComponents();
        c.mudaFonte(this, 18);
        this.frm = frm; 
        conVenda.fillCboClient(cboCliente);
        this.usuario = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cboCliente = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtContactoCli = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        lblExtTot = new javax.swing.JLabel();
        lblExtPago = new javax.swing.JLabel();
        lblExtTroc = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtValorPago = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        lblTrocos = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnEmitir = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        lblCodProd = new javax.swing.JLabel();
        lblIdVendaLinha = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCarregar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 180, 204));
        setLayout(new java.awt.GridLayout(1, 0, 0, 5));

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.CardLayout(30, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 230));
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout(0, 15));

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(3, 0, 0, 2));

        jPanel21.setOpaque(false);
        jPanel21.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel12.setText("Cliente");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel21.add(jLabel12, java.awt.BorderLayout.LINE_START);

        cboCliente.setBackground(new java.awt.Color(0, 102, 102));
        cboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descolhecido", "Blabla" }));
        cboCliente.setOpaque(false);
        cboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClienteActionPerformed(evt);
            }
        });
        jPanel21.add(cboCliente, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel21);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Sylfaen", 0, 14)); // NOI18N
        jLabel11.setText("Contacto");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel9.add(jLabel11, java.awt.BorderLayout.LINE_START);

        txtContactoCli.setEditable(false);
        txtContactoCli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtContactoCli.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContactoCli.setText("+258 8499 77 555");
        txtContactoCli.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtContactoCli.setEnabled(false);
        txtContactoCli.setOpaque(false);
        txtContactoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactoCliActionPerformed(evt);
            }
        });
        txtContactoCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactoCliKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactoCliKeyTyped(evt);
            }
        });
        jPanel9.add(txtContactoCli, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel9);

        jPanel1.add(jPanel6);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 15, 0));
        jPanel1.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(4, 0));
        jPanel5.add(jLabel1);
        jPanel5.add(jLabel2);
        jPanel5.add(jLabel3);

        jPanel1.add(jPanel5);

        jPanel8.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255)));
        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 15, 0));

        jPanel18.setOpaque(false);
        jPanel18.setLayout(new java.awt.GridLayout(3, 0));

        lblExtTot.setForeground(new java.awt.Color(51, 0, 51));
        lblExtTot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExtTot.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 204, 255)));
        jPanel18.add(lblExtTot);

        lblExtPago.setForeground(new java.awt.Color(51, 0, 51));
        lblExtPago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExtPago.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 204, 255)));
        jPanel18.add(lblExtPago);

        lblExtTroc.setForeground(new java.awt.Color(51, 0, 51));
        lblExtTroc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel18.add(lblExtTroc);

        jPanel2.add(jPanel18);

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.GridLayout(1, 5, 20, 0));

        jPanel14.setOpaque(false);
        jPanel14.setLayout(new java.awt.GridLayout(3, 0));

        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 204, 255)));
        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.GridLayout(1, 4, 10, 3));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Total a pagar");
        jPanel17.add(jLabel7);

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTotal.setText("0.00");
        lblTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel17.add(lblTotal);

        jPanel14.add(jPanel17);

        jPanel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(102, 204, 255)));
        jPanel19.setOpaque(false);
        jPanel19.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Valor pago");
        jPanel19.add(jLabel10);

        txtValorPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValorPagoKeyReleased(evt);
            }
        });
        jPanel19.add(txtValorPago);

        jPanel14.add(jPanel19);

        jPanel20.setOpaque(false);
        jPanel20.setLayout(new java.awt.GridLayout(1, 4, 10, 3));

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Trocos");
        jPanel20.add(jLabel19);

        lblTrocos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrocos.setText("0.00");
        lblTrocos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel20.add(lblTrocos);

        jPanel14.add(jPanel20);

        jPanel15.add(jPanel14);

        jPanel16.setOpaque(false);
        jPanel16.setLayout(new java.awt.GridLayout(3, 0));

        btnCalcular.setBackground(new java.awt.Color(0, 153, 102));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calcular.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCalcular.setOpaque(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel16.add(btnCalcular);

        btnEmitir.setBackground(new java.awt.Color(0, 153, 102));
        btnEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/confirm.png"))); // NOI18N
        btnEmitir.setText("Emitir");
        btnEmitir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEmitir.setOpaque(false);
        btnEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmitirActionPerformed(evt);
            }
        });
        jPanel16.add(btnEmitir);

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/list.png"))); // NOI18N
        jButton4.setText("Imprimir");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton4);

        jPanel15.add(jPanel16);

        jPanel2.add(jPanel15);

        jPanel8.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout(0, 2));

        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel10.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.BorderLayout());

        lblCodProd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel13.add(lblCodProd, java.awt.BorderLayout.CENTER);

        lblIdVendaLinha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdVendaLinha.setText("         ");
        lblIdVendaLinha.setPreferredSize(new java.awt.Dimension(60, 14));
        jPanel13.add(lblIdVendaLinha, java.awt.BorderLayout.LINE_START);

        jPanel10.add(jPanel13);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        jButton2.setBackground(new java.awt.Color(204, 51, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remov.png"))); // NOI18N
        jButton2.setText("Remover da lista");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton2);

        btnImprimir.setBackground(new java.awt.Color(0, 153, 102));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/limpar.png"))); // NOI18N
        btnImprimir.setText("Limpar");
        btnImprimir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnImprimir.setOpaque(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel12.add(btnImprimir);

        btnCarregar.setBackground(new java.awt.Color(0, 153, 102));
        btnCarregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/list.png"))); // NOI18N
        btnCarregar.setText("Agregar Produto");
        btnCarregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCarregar.setOpaque(false);
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });
        jPanel12.add(btnCarregar);

        jPanel10.add(jPanel12);

        jPanel3.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.BorderLayout(3, 0));

        tab.setBackground(new java.awt.Color(33, 210, 224));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO DO PRODUTO", "QUANTIDADE", "VALOR UNITARIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setMinWidth(60);
            tab.getColumnModel().getColumn(0).setMaxWidth(60);
            tab.getColumnModel().getColumn(2).setMinWidth(150);
            tab.getColumnModel().getColumn(2).setMaxWidth(150);
            tab.getColumnModel().getColumn(3).setMinWidth(150);
            tab.getColumnModel().getColumn(3).setMaxWidth(150);
            tab.getColumnModel().getColumn(4).setMinWidth(150);
            tab.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        jPanel11.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel8.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, "card2");

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents

    private void cboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteActionPerformed
        String s = val.pegaTxt(cboCliente);
        conVenda.on_cchangeCboClient(txtContactoCli, s);
    }//GEN-LAST:event_cboClienteActionPerformed

    private void txtContactoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoCliActionPerformed

    private void txtContactoCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoCliKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoCliKeyPressed

    private void txtContactoCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactoCliKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactoCliKeyTyped

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        new frmCarregarProd(frm, tab, lstCarregar).setVisible(true);
        frm.setEnabled(false);
        // conVenda.fillCboClient(cboCliente);
    }//GEN-LAST:event_btnCarregarActionPerformed

    void limpar(Venda v) {
        if (v == null) {
            val.poeTxt(lblCodProd, "");
            val.poeTxt(lblIdVendaLinha, "");
            conVenda.listarNaTabelaCarregar(tab, lstCarregar);
        } else {
            val.poeTxt(lblCodProd, v.getCodigoProd());
            val.poeTxt(lblIdVendaLinha, "" + v.getId());
        }
    }
    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        if (tab.getSelectedRow() != -1) {
            indice = (Integer) tab.getValueAt(tab.getSelectedRow(), 0);
            Venda v = lstCarregar.get(indice - 1);
            if (v != null) {
                limpar(v);
            }
        } else {
            val.msg(tab, "Erro de listagem.");
        }
    }//GEN-LAST:event_tabMouseClicked
    int getIdToRemove() {
        int s = val.e_int(lblIdVendaLinha);
        if (s > -1) {
            return s - 1;
        }
        return -1;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = getIdToRemove();
        if (id >= 0) {
            if (val.msgConfirm(jButton2, "Esse registo sera removido.")) {
                Venda v = lstCarregar.get(id);
                lstCarregar.remove(v);
                limpar(null);
            }
        } else {
            val.msg(jButton2, "Selecione a linha a remover.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean calcular(boolean salvar) {
        int id = 0;
        boolean activo = true;
        String codigoProd; // sera: id/nome
        String codigoCliente = val.pegaTxt(cboCliente);

        int quantidade;
        double valorUnitProd;
        double valorDesconto = 0;
        double totalVenda;
        double totalProd;
        double totalPago = val.e_double(val.pegaTxt(txtValorPago));
        double totalTroco = val.e_double(val.pegaTxt(lblTrocos));
        String dataVenda = dh.getData() + " - " + dh.getHoras();
        String estado = "emitido";
        ArrayList<Venda> l = new ArrayList<>();
        if (lstCarregar.size() > 0) {
            double soma = 0, muil = 0;
            for (Venda o : lstCarregar) {
                codigoProd = o.getCodigoProd();
                quantidade = o.getQuantidade();
                valorUnitProd = o.getValorUnitProd();
                muil += (quantidade * valorUnitProd);
                totalProd = muil;
                o.setTotalProd(totalProd);
                o.setTotalTroco(totalTroco);
                o.setDataVenda(dataVenda);
                o.setEstado(estado);
                o.setCodigoCliente(codigoCliente);
                soma += muil;
                l.add(o);
            }
            val.poeTxt(lblTotal, "" + dim(soma, 2));
            lblExtTot.setText(ex.getExtenso(so("" + soma)));

            if (salvar) {
                if (totalPago >= soma) {
                    val.poeTxt(lblTrocos, "" + dim((totalPago - soma), 2));
                    lblExtTroc.setText(ex.getExtenso(so("" + (totalPago - soma))));
                    for (Venda o : l) {
                        o.setUsuario(usuario);
                        o.setTotalVenda(soma);
                        o.setTotalPago(totalPago);
                        int idProd = val.e_int(val.extraiAPrimeiraOcorrencia(o.getCodigoProd(), '/'));
                        if (idProd > 0) {
                            Produto p = conProd.pesquisar(idProd);
                            if (p != null) {
                                conVenda.cadastrar(o);
                                p.setQuantidade(p.getQuantidade() - o.getQuantidade());
                                conProd.actualizar(p);
                            } else {
                                val.msg(btnCalcular, "Produto nao encontrado 2.");
                            }
                        } else {
                            val.msg(btnCalcular, "Produto nao encontrado 1.");
                        }
                    }
                    val.msg(btnEmitir, "Emitido");
                    limpar(false);
                    return true;
                } else {
                    val.msg(btnCalcular, "Pagou um valor insuficiente.");
                }
            }
        } else {
            val.msg(btnCalcular, "Tabela vazia");
        }
        return false;
    }

    void limpar(boolean tudo) {
        if (tudo) {
            val.poeTxt(txtContactoCli, "");
            val.poeTxt(txtValorPago, "");
            val.poeTxt(lblCodProd, "");
            val.poeTxt(lblIdVendaLinha, "");
            val.poeTxt(lblTotal, "0.0");
            val.poeTxt(lblTrocos, "0.0");

            val.poeTxt(lblExtTot, "zero");
            val.poeTxt(lblExtPago, "zero");
            val.poeTxt(lblExtTroc, "zero");

            lstCarregar = new ArrayList<>();
            conVenda.listarNaTabelaCarregar(tab, lstCarregar);
        }
        btnCalcular.setEnabled(tudo);
        btnEmitir.setEnabled(tudo);
        txtValorPago.setEnabled(tudo);
    }
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        calcular(false);
    }//GEN-LAST:event_btnCalcularActionPerformed
    Extenso ex = new Extenso();


    private void btnEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmitirActionPerformed
        calcular(true);
    }//GEN-LAST:event_btnEmitirActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        limpar(true);
    }//GEN-LAST:event_btnImprimirActionPerformed
    String so(String a) {
        return val.extraiAPrimeiraOcorrencia(a, '.');
    }

    double dim(double v, int i) {
        return val.diminuiCasasDecimais(v, i);
    }
    private void txtValorPagoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorPagoKeyReleased
        lblExtPago.setText(ex.getExtenso(so(val.pegaTxt(txtValorPago))));
        double a_pagar = val.e_double(val.pegaTxt(lblTotal));
        double totalPago = val.e_double(txtValorPago);
        double r = totalPago - a_pagar;
        if (r >= 0) {
            lblExtTroc.setText(ex.getExtenso(so("" + (int) r)));
            val.poeTxt(lblTrocos, "" + dim(r, 2));
        } else {
            lblExtTroc.setText("");
            val.poeTxt(lblTrocos, "0.0");
        }
        if (val.pegaTxt(txtValorPago).length() > 1) {
            calcular(false);
        }
    }//GEN-LAST:event_txtValorPagoKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        imp.imprimirVenda(lstCarregar, false);
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnEmitir;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodProd;
    private javax.swing.JLabel lblExtPago;
    private javax.swing.JLabel lblExtTot;
    private javax.swing.JLabel lblExtTroc;
    private javax.swing.JLabel lblIdVendaLinha;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTrocos;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtContactoCli;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables

}
