/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controles.ControlaProdutos;
import Controles.ControlaVenda;
import JARs.Componentes;
import JARs.DateTime;
import JARs.Validacoes;
import Modelos.Fornecedor;
import Modelos.Produto;
import Modelos.Venda;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import static jdk.nashorn.internal.objects.NativeString.toUpperCase;

/**
 *
 * @author Marondo
 */
public class frmCarregarProd extends javax.swing.JFrame {

    Validacoes val = new Validacoes();
    Componentes c = new Componentes();
    Fornecedor selectedForn = null;
    Produto selectedProd = null;
    ControlaProdutos conProd = new ControlaProdutos();
    ControlaVenda conVenda = new ControlaVenda();
    DateTime dh = new DateTime();
    JFrame frm;
//     JButton btn; 
    int indice = 0;
    JTable tbl;
    ArrayList<Venda> lstCarregar;

    public frmCarregarProd(JFrame frm, JTable tbl, ArrayList<Venda> lstCarregar) {
        initComponents();
        setSize(1100, 350);
        setLocationRelativeTo(this);
//        val.disposeOnClick(this, lblOk);
//        val.exitOnClick(lblExit);
        val.droaggForm(this);
        c.mudaFonte(pFundo, 18);
        this.frm = frm;
        this.tbl = tbl;
        this.lstCarregar = lstCarregar;
        openFrm(false);

        conProd.fillCbo_Forn_Emb_Tipo(cboFornecedor, cboEmb, cboTipo);
        pesquisar();
    }

    public frmCarregarProd() {
        initComponents();
        setSize(1100, 350);
        setLocationRelativeTo(this);
        val.exitOnClick(lblExit);
        val.droaggForm(this);
        c.mudaFonte(pFundo, 18);

        conProd.fillCbo_Forn_Emb_Tipo(cboFornecedor, cboEmb, cboTipo);
        pesquisar();
    }

    public void openFrm(boolean open) {//,JButton btn
        if (open) {
            frm.setEnabled(false);
            setVisible(true);
        } else {
            frm.setEnabled(true);
            dispose();
        }
    }

    void pesquisar() {
        String forn = val.pegaTxt(cboFornecedor), emb = val.pegaTxt(cboEmb);
        String tip = val.pegaTxt(cboTipo), search = val.pegaTxt(txtPesq);
        conProd.listarNaTabelaCarregar(tab, forn, emb, tip, search);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pFundo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        pDroag = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboFornecedor = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cboEmb = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPesq = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        pFundo.setBackground(new java.awt.Color(0, 204, 204));
        pFundo.setLayout(new java.awt.CardLayout(2, 2));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255)));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.CardLayout(2, 2));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(2, 0));

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(850, 120));
        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 2, 5));

        pDroag.setOpaque(false);
        pDroag.setLayout(new java.awt.CardLayout(2, 2));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(74, 26));
        jPanel10.setLayout(new java.awt.GridLayout(1, 2, 2, 0));
        jPanel10.add(jLabel1);

        lblExit.setBackground(new java.awt.Color(255, 51, 51));
        lblExit.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close_32.png"))); // NOI18N
        lblExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit.setOpaque(true);
        lblExit.setPreferredSize(new java.awt.Dimension(40, 40));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        jPanel10.add(lblExit);

        jPanel9.add(jPanel10, java.awt.BorderLayout.LINE_END);

        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(74, 26));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel11, java.awt.BorderLayout.LINE_START);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SELECIONAR E ADICIONAR PRODUTOS A LISTA DE VENDA");
        jPanel9.add(jLabel5, java.awt.BorderLayout.CENTER);

        pDroag.add(jPanel9, "card2");

        jPanel3.add(pDroag);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(1, 5, 5, 0));

        jPanel15.setOpaque(false);
        jPanel15.setLayout(new java.awt.BorderLayout(30, 0));

        jPanel16.setOpaque(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(380, 36));
        jPanel16.setLayout(new java.awt.BorderLayout(15, 0));

        jPanel13.setOpaque(false);
        jPanel13.setPreferredSize(new java.awt.Dimension(150, 14));
        jPanel13.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel11.setText("Quantidade");
        jPanel13.add(jLabel11, java.awt.BorderLayout.LINE_START);

        txtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantActionPerformed(evt);
            }
        });
        jPanel13.add(txtQuant, java.awt.BorderLayout.CENTER);

        jPanel16.add(jPanel13, java.awt.BorderLayout.LINE_START);

        jPanel14.setLayout(new java.awt.GridLayout(1, 3, 2, 0));

        btnAdd.setBackground(new java.awt.Color(0, 153, 102));
        btnAdd.setText("Adicionar");
        btnAdd.setOpaque(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel14.add(btnAdd);

        jButton3.setBackground(new java.awt.Color(255, 204, 0));
        jButton3.setText("Fechar");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton3);

        jPanel16.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel16, java.awt.BorderLayout.LINE_END);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel10.setText("Produto");
        jPanel8.add(jLabel10, java.awt.BorderLayout.LINE_START);

        txtProduto.setEditable(false);
        jPanel8.add(txtProduto, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel15);

        jPanel3.add(jPanel4);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel2.setText("Fornecedor");
        jPanel6.add(jLabel2, java.awt.BorderLayout.LINE_START);

        cboFornecedor.setBackground(new java.awt.Color(0, 102, 102));
        cboFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboFornecedor.setOpaque(false);
        cboFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboFornecedorActionPerformed(evt);
            }
        });
        jPanel6.add(cboFornecedor, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel3.setText("Embalagem");
        jPanel7.add(jLabel3, java.awt.BorderLayout.LINE_START);

        cboEmb.setBackground(new java.awt.Color(0, 102, 102));
        cboEmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboEmb.setOpaque(false);
        cboEmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboEmbActionPerformed(evt);
            }
        });
        jPanel7.add(cboEmb, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7);

        jPanel17.setOpaque(false);
        jPanel17.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel4.setText("Tipo");
        jPanel17.add(jLabel4, java.awt.BorderLayout.LINE_START);

        cboTipo.setBackground(new java.awt.Color(0, 102, 102));
        cboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Garafa de Vidro", "Garafa Plastica", "Pacote" }));
        cboTipo.setOpaque(false);
        cboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoActionPerformed(evt);
            }
        });
        jPanel17.add(cboTipo, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel17);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setOpaque(false);
        jPanel12.setPreferredSize(new java.awt.Dimension(300, 40));
        jPanel12.setLayout(new java.awt.BorderLayout(2, 0));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_16.png"))); // NOI18N
        jPanel12.add(jLabel6, java.awt.BorderLayout.LINE_END);

        jLabel7.setText("Nome");
        jPanel12.add(jLabel7, java.awt.BorderLayout.LINE_START);

        txtPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesqActionPerformed(evt);
            }
        });
        txtPesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesqKeyReleased(evt);
            }
        });
        jPanel12.add(txtPesq, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel12);

        jPanel3.add(jPanel5);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        tab.setBackground(new java.awt.Color(33, 210, 224));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCRICAO", "QUANT", "PRECO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab);
        if (tab.getColumnModel().getColumnCount() > 0) {
            tab.getColumnModel().getColumn(0).setMinWidth(60);
            tab.getColumnModel().getColumn(0).setMaxWidth(60);
            tab.getColumnModel().getColumn(2).setMaxWidth(80);
            tab.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, "card2");

        pFundo.add(jPanel1, "card2");

        getContentPane().add(pFundo, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
        if (tab.getSelectedRow() != -1) {
            indice = (Integer) tab.getValueAt(tab.getSelectedRow(), 0);
            String s = "";
            selectedProd = (Produto) conProd.pesquisar(indice);
            if (selectedProd != null) {
                s = selectedProd.getId() + "/" + selectedProd.getNome();
            }
            val.poeTxt(txtProduto, s);
        } else {
            val.msg(tab, "Erro de listagem.");
        }
    }//GEN-LAST:event_tabMouseClicked

    private void cboFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboFornecedorActionPerformed
        pesquisar();
    }//GEN-LAST:event_cboFornecedorActionPerformed

    private void cboEmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboEmbActionPerformed
        pesquisar();
    }//GEN-LAST:event_cboEmbActionPerformed

    private void txtPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesqActionPerformed

    }//GEN-LAST:event_txtPesqActionPerformed
    void pesquisarProd() {
        String t = toUpperCase(val.pegaTxt(txtPesq));
        ArrayList<Produto> l = new ArrayList<>();
        for (Produto o : conProd.lstProduto()) {
            String n = toUpperCase(o.getNome());
            if (n.contains(t)) {
                l.add(o);
            }
        }
        conProd.listarNaTabela(tab, l);
    }
    private void txtPesqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesqKeyReleased
//        pesquisarProd();
        pesquisar();
    }//GEN-LAST:event_txtPesqKeyReleased
    void limpar() {
        val.poeTxt(txtProduto, "");
        val.poeTxt(txtQuant, "");
        selectedProd = null;
    }

    Venda pegaDadosProd(Produto p, int q) {
        boolean activo = true;
        String codigoProd = p.getId() + "/" + p.getNome();
        String codigoCliente = "1/Desconhecido";

        int quantidade = q;
        double valorUnitProd = p.getPrecoVenda();
        double valorDesconto = 0;
        double totalVenda = (q * valorUnitProd);
        double totalPago = 0;
        double totalTroco = 0;
        String dataVenda = dh.getData();
        return new Venda(activo, codigoProd, codigoCliente, quantidade, valorUnitProd, valorDesconto, totalVenda, totalPago, totalTroco, dataVenda, "carregado", 0, "");
    }

    int existeVenda(String codProd) {
        int i = 0;
        for (Venda v : lstCarregar) {
            String s = v.getCodigoProd();
            if (s.equalsIgnoreCase(codProd)) {
                return i;
            }
            i++;
        }
        return -1;
    }

    void adicionar() {
        int qtd = val.e_int(txtQuant), qtdProd = 0;
        if (selectedProd != null) {
            qtdProd = selectedProd.getQuantidade();
            if (qtd > 0) {
                if (qtdProd >= qtd) {
                    Venda v = pegaDadosProd(selectedProd, qtd);
                    int i = existeVenda(v.getCodigoProd());
                    if (i == -1) {
                        lstCarregar.add(v);
                    } else {
                        if (val.msgConfirm(tbl, "Este produto ja existe na lista.\n"
                                + "Deseja alterar para este novo produto?")) {
                            lstCarregar.set(i, v);
                        }
                    }
                    conVenda.listarNaTabelaCarregar(tbl, lstCarregar);
                    limpar();
                } else {
                    val.msg(btnAdd, "A quantidade digitada nao deve ser maior que o stock.");
                }
            } else {
                val.msg(btnAdd, "Quantidade invalida.\nInforme quantos " + selectedProd.getNome() + " deseja.");
            }
        } else {
            val.msg(btnAdd, "Pesquise ou selecione um produto na tabela.");
        }
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        adicionar();
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        openFrm(false);        // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        openFrm(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoActionPerformed
        pesquisar();
    }//GEN-LAST:event_cboTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarregarProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarregarProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cboEmb;
    private javax.swing.JComboBox<String> cboFornecedor;
    private javax.swing.JComboBox<String> cboTipo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblExit;
    private javax.swing.JPanel pDroag;
    private javax.swing.JPanel pFundo;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtPesq;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuant;
    // End of variables declaration//GEN-END:variables
}
